apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 1h
  chart:
    spec:
      version: 1.6.0
      chart: pyroscope
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  values:
    serviceAccount:
      create: false
    agent:
      enabled: false