apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 1h
  chart:
    spec:
      version: 1.23.3
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  values:
    serviceAccount:
      create: false
    tempo:
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write"