apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely
  namespace: causely-mediation
spec:
  interval: 1h
  chart:
    spec:
      chart: causely
      version: 0.0.38-0-g97c4863c949c1a69
      sourceRef:
        kind: HelmRepository
        name: causely
        namespace: causely-mediation
