apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: causely
  namespace: causely-mediation
spec:
  interval: 12h
  type: oci
  url: oci://us-docker.pkg.dev/public-causely/public
