apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      persistence:
        enabled: true
      additionalDataSources:
        - name: Loki
          access: proxy
          editable: false
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          version: 1
        - name: Pyroscope
          access: proxy
          editable: false
          type: grafana-pyroscope-datasource
          url: http://pyroscope.monitoring.svc.cluster.local:4040
          version: 1
        - name: Tempo
          access: proxy
          editable: false
          type: tempo
          url: http://tempo.monitoring.svc.cluster.local:3200
          jsonData:
            httpMethod: GET
            serviceMap:
              datasourceUid: 'prometheus'
            nodeGraph:
              enabled: true
          version: 1
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus:
      prometheusSpec:
        enableOTLPReceiver: true
        enableRemoteWriteReceiver: true
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        tsdb:
          outOfOrderTimeWindow: 30m
        resources:
          requests:
            memory: 8192Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 50Gi
  postRenderers:
    - kustomize:
        patches:
          - target:
              # Ignore these objects from Flux diff as they are mutated from chart hooks
              kind: (ValidatingWebhookConfiguration|MutatingWebhookConfiguration)
              name: kube-prometheus-stack-admission
            patch: |
              - op: add
                path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                value: disabled
          - target:
              # Ignore these objects from Flux diff as they are mutated at apply time but not at dry-run time
              kind: PrometheusRule
            patch: |
              - op: add
                path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                value: disabled