apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely
  namespace: causely-mediation
spec:
  interval: 1h
  chart:
    spec:
      chart: causely
      version: v1.0.52-0-ge3434ff7eb603d0b
      sourceRef:
        kind: HelmRepository
        name: causely
        namespace: causely-mediation
