apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/addons/prometheus.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/addons/extras/prometheus-operator.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/addons/kiali.yaml