apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 1h
  chart:
    spec:
      chart: base
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
  interval: 1h
  chart:
    spec:
      chart: istiod
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio
