apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 1h
  chart:
    spec:
      chart: base
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
  interval: 1h
  chart:
    spec:
      chart: istiod
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    meshConfig:
      defaultProviders:
        metrics:
          - "prometheus"
        tracing:
          - "opentelemetry"
      extensionProviders:
        - name: opentelemetry
          opentelemetry:
            service: "grafana-agent.monitoring.svc.cluster.local"
            port: "4317"
