apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely-backend
  namespace: causely
spec:
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  interval: 1h
  chart:
    spec:
      chart: backend
      version: v1.0.92-0-g032e39faaf05c408
      sourceRef:
        kind: HelmRepository
        name: production-causely
        namespace: causely
