apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system
  interval: 1h
  chart:
    spec:
      chart: gateway
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
