apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely-backend
  namespace: causely
spec:
  interval: 1h
  chart:
    spec:
      chart: helm/backend
      version: v1.0.52-0-ge3434ff7eb603d0b
      sourceRef:
        kind: GitRepository
        name: causely
        namespace: flux-system
