apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely-backend
  namespace: causely
spec:
  interval: 1h
  chart:
    spec:
      chart: helm/backend
      version: v1.0.77-0-ga003eadf8f7d9cdb
      sourceRef:
        kind: GitRepository
        name: causely
        namespace: flux-system
