apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: causely
  namespace: flux-system
spec:
  interval: 12h
  url: ssh://git@github.com/Causely/causely
  secretRef:
    name: flux-system
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include helm/backend directory
    !/helm
